# -*- coding: utf-8 -*-
"""M02-Projeto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qK1GBETyLtacodWbodHf1JP-zVOdIoPR
"""

from mmap import MAP_SHARED
jogador1 = input('-> Digite o nome do primeiro jogador:')
jogador2 = input('-> Digite o nome do segundo jogador:')

print(f'// Quem escolhe primeiro, {jogador1} ou {jogador2}?')
primeiro_jogador = input(f'-> Digite 1 para esscolher {jogador1} ou Digite 2 para escolhe {jogador2}.')
segundo_jogador = None

if primeiro_jogador == "1":
  primeiro_jogador = jogador1
  segundo_jogador = jogador2
elif primeiro_jogador == "2":
  primeiro_jogador = jogador2
  segundo_jogador = jogador1

print('// Digite 0 para ecolher PAR ou 1 para escolher IMPAR.')
escolha1 = input(f'-> {primeiro_jogador}, você quer par ou impar?')
escolha2 = None

if escolha1 == 'ímpar' or escolha1 == 'impar' or escolha1 == '1':
  escolha1 = 'ímpar'
  escolha2 = 'par'
elif escolha1 == 'par' or escolha1 == '0':
  escolha1 = 'par'
  escolha2 = 'ímpar'

print(f'// {segundo_jogador}, você ficou com {escolha2} e o outro jogador escolheu {escolha1}.')

numero1 = int(input(f'-> {primeiro_jogador}, escolha um número:'))
numero2 = int(input(f'-> {segundo_jogador}, escolha um número:'))

soma = numero1 + numero2
if soma % 2 == 0:
  vencedor = 'par'
else:
  vencedor = 'ímpar'

if vencedor == escolha1:
  print(f'// {primeiro_jogador} venceu!')
else:
  print(f'// {segundo_jogador} venceu!')